### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by timsneath** [thlorenz/batufo#1]
Hey -- this looks really cool! A few of us here on the Flutter team would love to take a look at it, but there's no license at present so we're contractually unable to inspect the code. 

Would you be willing to consider licensing this using an open license like MIT or BSD (or any license really, just so we know where we stand!)

Thanks, Tim

**Comment by thlorenz** [comment]
Hey .. sounds awesome, would GPL2 work as well?

**Comment by thlorenz** [comment]
The reason why I'd prefer that over MIT is that I want any work based on this to be open source as well so all of us can learn from it.

**Comment by timsneath** [comment]
Oh sure. GPL2 works just fine!
